version: '3.7'

services:
  pytest:
    shm_size: 2gb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results && allure generate --clean -o allure-report allure-results"
    working_dir: /usr/workspace
    environment:
      - HOST=${HOST:-http://www.msp.lan}
      - HEADLESS=true

  allure:
    image: 'frankescobar/allure-docker-service'
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - '5050:5050'
    volumes:
      - ./allure-results:/app/allure-results

  allure-ui:
    image: 'frankescobar/allure-docker-service-ui'
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: 'http://localhost:5050'
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ''
    ports:
      - '5252:5252'
    depends_on:
      - allure
